---
title: "Sex Differences Analysis"
author: "Kevin Donovan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("Sex_Diff_LongData_6_27.RData")
load("Sex_Diff_WideData_6_27.RData")

#load("Sex_Diff_LongData_Old_6_27.RData")
#load("Sex_Diff_WideData_Old_6_27.RData")


library(tidyverse)
library(nlme)
library(kableExtra)
library(stats)
library(psych)
library(nFactors)
library(formula.tools)
library(ggpubr)
library(lavaan)
library(lavaanPlot)
library(DiagrammeR)
#library(Rgraphviz)
library(multiplex)
library(RColorBrewer)
library(lcmm)
library(gtsummary)
library(flextable)

# dataset_long <- dataset_long_old %>%
#   mutate(visit_num = as.numeric(gsub("V","",Visit)))

dataset_long <- dataset_long %>%
  mutate(visit_num = as.numeric(gsub("V","",Visit)))
```

# Data Exploration
```{r data_explore}
# Create time-specific social and RRB composites using means
dataset_long_explore <-
  dataset_long %>%
  mutate(social_factor = 
           ifelse(visit_num==6|visit_num==9|visit_num==12|visit_num==15, 
                  (aosi_q8_eye_contact+aosi_q3_orients_to_name_score+
                     aosi_q14_social_interest_recode+
                    aosi_q21_social_referencing+
                     aosi_q5_anticipatory_response_score_recode+
                    aosi_q9_reciprocal_social_smile_recode)/6,
                  ifelse(visit_num==24|visit_num==36,
                         (ADOS_Comb_EC+ADOS_Comb_RespName+ADOS_Comb_ShEnj+ADOS_Comb_Show+
                           ADOS_Comb_QSO+ADOS_Comb_Point+ADOS_Comb_Face)/8, NA)),
         rrb_factor=
           ifelse(visit_num==6|visit_num==9|visit_num==12|visit_num==15,
                  (aosi_q10_coordination_of_eye_gaze_and_action_recode+
                     aosi_q17_atypical_motor+
                     aosi_q18_atypical_sensory+aosi_q19_engagement_of_attention+
                     aosi_q16_motor_control_and_behaviour)/5,
                  ifelse(visit_num==24|visit_num==36,
                         (ADOS_Comb_HFMann+ADOS_Comb_SensInt+ADOS_Comb_RepBeh)/3, NA)))

# Now plot
ggplot(dataset_long_explore,
       mapping=aes(x=visit_num, y=social_factor, color=V24_Group, linetype=Gender_Dummy))+
  geom_point(position = position_dodge2(width = 0.75), size=2.5)+
  geom_smooth(method="lm", size=2.5)+
  xlab("Visit (months)")+
  ylab("Mean social score")+
  labs(color="24 month group",
       linetype="Sex")+
  theme_bw()+
    theme(text = element_text(size=30))
ggsave(filename = "Plots_Tables/explore_social_means.jpg", limitsize = FALSE,
       scale=2.5)

ggplot(dataset_long_explore %>% filter(visit_num!=36),
       mapping=aes(x=visit_num, y=rrb_factor, color=V24_Group, linetype=Gender_Dummy))+
  geom_point(position = position_dodge2(width = 0.75), size=2.5)+
  geom_smooth(method="lm", size=2.5)+
  xlab("Visit (months)")+
  ylab("Mean RRB score")+
  labs(color="24 month group",
       linetype="Sex")+
  theme_bw()+
    theme(text = element_text(size=30))
ggsave(filename = "Plots_Tables/explore_rrb_means.jpg", limitsize = FALSE,
       scale=2.5)
```

# Exploratory Factor Analysis

```{r factor_analysis_v0}
formula_list <- list()
formula_list[["6_months"]] <- list("all_aosi"=as.formula(paste("~", 
                paste(names(dataset_long)[grepl(x=names(dataset_long), 
                                                pattern = "aosi")&!
                                            grepl(x=names(dataset_long), 
                                                pattern = "DONOTUSE|total_score")], 
                      collapse = " + "))),
                "all_social"=~aosi_q8_eye_contact+aosi_q3_orients_to_name_score+
                  aosi_q14_social_interest_recode+aosi_q21_social_referencing+
                  aosi_q5_anticipatory_response_score_recode+
                  aosi_q9_reciprocal_social_smile_recode,
                "all_rrb"=~aosi_q10_coordination_of_eye_gaze_and_action_recode+
                  aosi_q17_atypical_motor+aosi_q18_atypical_sensory+
                  aosi_q19_engagement_of_attention+aosi_q16_motor_control_and_behaviour)

formula_list[["12_months"]] <- formula_list[["6_months"]]
formula_list[["24_months"]] <- 
  list("all_ados"=as.formula(paste("~", 
                paste(names(dataset_long)[grepl(x=names(dataset_long), 
                                                pattern = "ADOS_Comb")&
                                            !grepl(x=names(dataset_long), 
                                                pattern = "V37plus")], 
                      collapse = " + "))),
                "all_social"=~ADOS_Comb_ShEnj+ADOS_Comb_SIJA+ADOS_Comb_Show+
                  ADOS_Comb_QSO+ADOS_Comb_Point+ADOS_Comb_Face,
                "all_rrb"=~ADOS_Comb_HFMann+ADOS_Comb_SensInt+ADOS_Comb_RepBeh)

formula_list[["36_months"]] <- formula_list[["24_months"]]
      
fa_fit <- list()
fa_crosssect_plots <- list()

## Cross-sectional factor analysis - Using all time specific items.
sex_list <- c("all", as.character(unique(dataset_long$Gender_Dummy))) 

# Only look at 6, 12, 24, 36 month results (9, 15 month too low n)
visits_of_interest <- c("V06", "V12", "V24", "V36")
for(j in 1:length(sex_list)){
  fa_fit[[sex_list[j]]] <- list()
  names(fa_fit)[j] <- sex_list[j]
  
  fa_crosssect_plots[[sex_list[j]]] <- list()
  names(fa_crosssect_plots)[j] <- sex_list[j]

  for(i in 1:length(visits_of_interest)){
      # Pick time point
      visit_select <- visits_of_interest[i]
      
      # Filter dataset
      if(sex_list[j]=="all"){
      dataset_long_visit <- dataset_long %>%
        filter(Visit==visit_select & Risk_dummy=="HR")
      } else {
        dataset_long_visit <- dataset_long %>%
        filter(Visit==visit_select & Risk_dummy=="HR"& Gender_Dummy==sex_list[j])
      }
      
      # Create objects
      fa_crosssect_plots[[sex_list[j]]][[i]] <- list()
      fa_fit[[sex_list[j]]][[i]] <- list()

      for(k in 1:length(formula_list[[i]])){
        # Specify variables of interest for factor analysis
        formula_select <- formula_list[[i]][[k]]
        factor_num <- 
          ifelse(names(formula_list[[i]])[k]%in%c("all_social","all_rrb"),1,2)
        
        ## Run factor analysis
        # First check scree plot (though we will also run selecting 2 factors)
        formula_vars <- formula.tools::rhs.vars(formula_select)
        x_var_data <- dataset_long_visit %>%
            select(formula_vars)
        
        eigen_values_cov <- 
          eigen(cov(x_var_data, use="pairwise.complete.obs"))

        fa_crosssect_plots[[sex_list[j]]][[i]][[k]] <- list()
        names(fa_crosssect_plots[[sex_list[j]]])[i] <-
          paste0("Visit = ", visit_select, ": HR data")
        
        names(fa_crosssect_plots[[sex_list[j]]][[i]])[k] <-
          names(formula_list[[i]])[k]
        png("test.png") 
        dev.control(displaylist="enable")
        plotuScree(x=eigen_values_cov$values)
        fa_crosssect_plots[[sex_list[j]]][[i]][[k]][["scree_plot"]] <- recordPlot()
        dev.off()
        unlink("test.png")
        
        # Fit factor analysis to data
        names(fa_fit[[sex_list[j]]])[i] <- paste0("Visit = ", 
                                                  visit_select, ": HR data")
        fa_fit[[sex_list[j]]][[i]][[k]] <- 
          fa(r=x_var_data, nfactors=factor_num,
             rotate = "varimax", fm="ml",alpha = 0.05)
          
        # Extract and format loading matrix
        loading_matrix_edit <-
          if(factor_num==2){
          data.frame(fa_fit[[sex_list[j]]][[i]][[k]]$loadings[,1:dim(fa_fit[[sex_list[j]]][[i]][[k]]$loadings)[2]]) %>%
          rownames_to_column() %>%
          pivot_longer(cols=c(`ML1`, `ML2`), 
                       names_to="factor_type", values_to="loading") %>%
          arrange(rowname, factor_type)
          }else{
            fa_fit[[sex_list[j]]][[i]][[k]]$loadings[,1:dim(fa_fit[[sex_list[j]]][[i]][[k]]$loadings)[2]]%>%
            data.frame() %>%
            plyr::rename(replace=c("."="ML1"))%>%
            rownames_to_column() %>%
          pivot_longer(cols=c(`ML1`), 
                       names_to="factor_type", values_to="loading") %>%
          arrange(rowname, factor_type)
          }
        
        # Plot loading values by factor in bar plot
        if(i%in%c(1,2)){
          split_x_labs <- strsplit(loading_matrix_edit$rowname, split="_")
          combine_split <- function(x){
            x_subset <- x[c(1,2)]
            return(paste(x_subset, collapse = "_"))
          }
          
          combine_x_labs <- unlist(lapply(X=split_x_labs, FUN=combine_split))
          loading_matrix_edit$rowname <- combine_x_labs
        }
  
        
        fa_crosssect_plots[[sex_list[j]]][[i]][[names(formula_list[[i]])[k]]][["loadings_plot"]] <-
        ggplot(data=loading_matrix_edit, mapping=aes(x=rowname, y=loading, fill=factor_type))+
          facet_grid(rows = factor_type~.)+
          geom_bar(stat = "Identity")+
          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
          labs(title = paste0("Factor loadings by component at visit ", visit_select),
               subtitle = paste0("HR data only; Sex=", sex_list[j]))
        
          fa.graph(fa.results = 
                fa_fit[[sex_list[j]]][[i]][[k]],
                digits = 2,
                out.file = 
                  paste0("EFA_Path_Code/","HR","_Sex_",
                         sex_list[j],"_Visit_",visit_select,".dot"))
          
        # Save fit statistics
        efa_fit_stats <- 
          data.frame("sex"=sex_list[j],
                     "visit"=unique(dataset_long$Visit)[i],
                     "model_name"=names(formula_list[[i]])[k],
                     "chi_sq_stat"=fa_fit[[sex_list[j]]][[i]][[k]]$STATISTIC,
                     "chi_sq_df"=fa_fit[[sex_list[j]]][[i]][[k]]$dof,
                     "ch_sq_pval"=
                       ifelse(fa_fit[[sex_list[j]]][[i]][[k]]$PVAL<0.005, "<0.005",
                              fa_fit[[sex_list[j]]][[i]][[k]]$PVA),
                     "tli"=fa_fit[[sex_list[j]]][[i]][[k]]$TLI,
                     "rmsea"=
                       ifelse(
                         length(fa_fit[[sex_list[j]]][[i]][[k]]$RMSEA["RMSEA"])==0,
                              NA,
                              fa_fit[[sex_list[j]]][[i]][[k]]$RMSEA["RMSEA"]),
                     "rmsea_95ci"=
                    ifelse(length(fa_fit[[sex_list[j]]][[i]][[k]]$RMSEA["RMSEA"])==0,
                           NA,
                              paste0("(",
                              round(fa_fit[[sex_list[j]]][[i]][[k]]$RMSEA["lower"],3),
                     ", ", 
                     round(fa_fit[[sex_list[j]]][[i]][[k]]$RMSEA["upper"],3),
                     ")")))
        base::row.names(efa_fit_stats) <- NULL
        
        fa_crosssect_plots[[sex_list[j]]][[i]][[names(formula_list[[i]])[k]]][["fit_stats"]] <- efa_fit_stats
        kable(x=fa_crosssect_plots[[sex_list[j]]][[i]][[names(formula_list[[i]])[k]]][["fit_stats"]], digits = 3) %>%
          kable_styling() %>%
          save_kable(file=paste0("Plots_Tables/efa/efa_2fac_fitstats_",
                                 "sex_",sex_list[j],
                                 "_visit_",unique(dataset_long$Visit)[i],
                                 "_model_",names(formula_list[[i]])[k],
                                 ".jpg"))
          
        fa_crosssect_plots[[sex_list[j]]][[i]][[names(formula_list[[i]])[k]]][["path_diagram"]] <- 
        grViz(diagram = paste0("EFA_Path_Code/","HR","_Sex_",
                         sex_list[j],"_Visit_",visit_select,".dot"))
      }
   }
}

ggarrange(fa_crosssect_plots$all$`Visit = V06: HR data`$all_aosi$loadings_plot,
                          fa_crosssect_plots$all$`Visit = V12: HR data`$all_aosi$loadings_plot,
            ncol=1, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_aosi_all_sex.png", scale=2.5, dpi=320, limitsize = FALSE)

ggarrange(fa_crosssect_plots$all$`Visit = V24: HR data`$all_ados$loadings_plot,
                          fa_crosssect_plots$all$`Visit = V36: HR data`$all_ados$loadings_plot,
            ncol=1, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_ados_all_sex.png", scale=2.5, dpi=320, limitsize = FALSE)


## Create loadings plots at each time point comparing males and females
# 6 and 12 months: AOSI
ggarrange(fa_crosssect_plots$female$`Visit = V06: HR data`$all_aosi$loadings_plot,
                          fa_crosssect_plots$female$`Visit = V12: HR data`$all_aosi$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V06: HR data`$all_aosi$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V12: HR data`$all_aosi$loadings_plot,
            ncol=2, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_aosi_comp_sex.png", scale=2.5, dpi=320, limitsize = FALSE)

# 24 and 36 months: ADOS
ggarrange(fa_crosssect_plots$female$`Visit = V24: HR data`$all_ados$loadings_plot,
                          fa_crosssect_plots$female$`Visit = V36: HR data`$all_ados$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V24: HR data`$all_ados$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V36: HR data`$all_ados$loadings_plot,
            ncol=2, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_ados_comp_sex.png", scale=2.5, dpi=320, limitsize = FALSE)

# All Social
ggarrange(fa_crosssect_plots$female$`Visit = V06: HR data`$all_social$loadings_plot,
                          fa_crosssect_plots$female$`Visit = V12: HR data`$all_social$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V06: HR data`$all_social$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V12: HR data`$all_social$loadings_plot,
            ncol=2, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_aosi_social_comp_sex.png", scale=2.5, dpi=320, limitsize = FALSE)

ggarrange(fa_crosssect_plots$female$`Visit = V24: HR data`$all_social$loadings_plot,
                          fa_crosssect_plots$female$`Visit = V36: HR data`$all_social$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V24: HR data`$all_social$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V36: HR data`$all_social$loadings_plot,
            ncol=2, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_ados_social_comp_sex.png", scale=2.5, dpi=320, limitsize = FALSE)

# All RRB
ggarrange(fa_crosssect_plots$female$`Visit = V06: HR data`$all_rrb$loadings_plot,
                          fa_crosssect_plots$female$`Visit = V12: HR data`$all_rrb$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V06: HR data`$all_rrb$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V12: HR data`$all_rrb$loadings_plot,
            ncol=2, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_aosi_rrb_comp_sex.png", scale=2.5, dpi=320, limitsize = FALSE)

ggarrange(fa_crosssect_plots$female$`Visit = V24: HR data`$all_rrb$loadings_plot,
                          fa_crosssect_plots$female$`Visit = V36: HR data`$all_rrb$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V24: HR data`$all_rrb$loadings_plot,
                          fa_crosssect_plots$male$`Visit = V36: HR data`$all_rrb$loadings_plot,
            ncol=2, nrow=2,
            common.legend = TRUE)
ggsave("Plots_Tables/efa/fa_all_ados_rrb_comp_sex.png", scale=2.5, dpi=320, limitsize = FALSE)
```

# Moderated Non-linear Factor Analysis

```{r mnlfa_v0}
# Add composite, overlapping variables to dataset
dataset_long_wcomps <- dataset_long %>%
      mutate(EYEC = ifelse(visit_num%in%c(6,9,12,15),
                           aosi_q8_eye_contact,ADOS_Comb_EC),
             RNAME = ifelse(visit_num%in%c(6,9,12,15),
                            aosi_q3_orients_to_name_score,
                            ADOS_Comb_RespName),
             SOCINT = ifelse(visit_num%in%c(6,9,12,15),
                             aosi_q14_social_interest_recode,
                             ADOS_Comb_ShEnj),
             SOCREF = ifelse(visit_num%in%c(6,9,12,15),aosi_q21_social_referencing,
                             ADOS_Comb_SIJA),
             MOTOR = ifelse(visit_num%in%c(6,9,12,15),aosi_q17_atypical_motor,
                            ADOS_Comb_HFMann),
             SENS = ifelse(visit_num%in%c(6,9,12,15),aosi_q18_atypical_sensory,
                           ADOS_Comb_SensInt))

harmonized_vars <- c("EYEC","RNAME","SOCINT","SOCREF","MOTOR","SENS")

# List of formulas
formula_list <- 
      list(~EYEC+RNAME+SOCINT+SOCREF+ADOS_Comb_Show+ADOS_Comb_QSO+
             aosi_q5_anticipatory_response_score_recode+
             aosi_q9_reciprocal_social_smile_recode,
           ~MOTOR+SENS+ADOS_Comb_RepBeh+aosi_q19_engagement_of_attention+
             aosi_q16_motor_control_and_behaviour)

path_list <-
  c("all_social",
    "all_rrb")

# Create numeric ID variable and gender variable
ids_num <- dataset_long_wcomps %>%
  select(Identifiers) %>%
  unique() %>%
  dim()

dataset_long_numids <-
  data.frame(dataset_long_wcomps %>%
  select(Identifiers) %>%
  unique(),
  "num_ids"=1:(ids_num[1]))
# Save to match back to OG ids
write_csv(dataset_long_numids, file="Docs/num_ids_og_ids_key.csv")

dataset_long_nums_all <- 
  dataset_long_wcomps %>%
  merge(dataset_long_numids) %>%
  mutate(V24_Dx=ifelse(V24_Group=="ASD", "ASD",
                       ifelse(V24_Group%in%c("Atypical","Typical"), "Negative", NA)),
         V24_Dx_num=ifelse(V24_Dx=="ASD",1,
                       ifelse(V24_Dx=="Negative",0,NA)),
         gender_num=ifelse(Gender_Dummy=="female", 1, 
                           ifelse(Gender_Dummy=="male",0,NA)),
         V36_Dx=ifelse(V36_ASD_dummy==c("Atypical","Typical"), 0,
                            ifelse(V36_ASD_dummy=="ASD",1,NA)),
         #V36_Dx=ifelse(V36_Dx==c("Atypical","Typical"), 0,
                            #ifelse(V36_Dx=="ASD",1,NA)),
         IQBIN = ifelse(mullen_composite_standard_score<
                          median(mullen_composite_standard_score,
                                 na.rm = TRUE), 0,
                        ifelse(is.na(mullen_composite_standard_score)==1, NA,
                               1)),
         DX_AGE=V24_Dx_num*Candidate_Age,
         DX_GNUM=V24_Dx_num*gender_num,
         DXGENCHA=ifelse(Gender_Dummy=="male"&V24_Dx=="ASD","male_ASD",
                           ifelse(Gender_Dummy=="male"&V24_Dx=="Negative","male_negative",
                                  ifelse(Gender_Dummy=="female"&V24_Dx=="ASD","female_ASD",
                                         ifelse(Gender_Dummy=="female"&V24_Dx=="Negative","female_negative",NA))))) %>%
  select(Identifiers, num_ids, Visit, visit_num, Gender_Dummy, gender_num, 
         everything()) %>%
  rename(c("ID"="num_ids", "VNUM"="visit_num","GNUM"="gender_num",
           "GCHAR"="Gender_Dummy",
           "IQMULL"="mullen_composite_standard_score",
           "DXV24"="V24_Dx_num")) #%>%
  #filter(Risk_dummy=="HR")

# Save dataset for summ stats
save(dataset_long_nums_all, file = "Data/fa_data_hr_lr.RData")

## Start loop
data_subset <- c("whole", "female", "male")
timepoints <- c("all", "6", "12", "24", "36")
iq_threshold <- "all"
# other IQ thresholds used: 85, median(dataset_long_nums$IQMULL, na.rm=TRUE)

efa_scree_plots <- list()
efa_1fact_fit <- list()
efa_1_plots <- list()
efa_1_full_plots <- list()

# # Run for both LR and HR
#risk_vals <- levels(dataset_long_nums_all$Risk_dummy)
# NOTE: can't run CFAs in LR group at certain time points due to 0 variability in some items in the RRB domain
risk_vals <- "HR"

for(r in 1:length(risk_vals)){  
  for(i in 1:length(path_list)){
    efa_scree_plots[[i]] <- list()
    efa_1fact_fit[[i]] <- list()
    efa_1_plots[[i]] <- list()
    
    names(efa_scree_plots)[i] <- path_list[i]
    names(efa_1fact_fit)[i] <- path_list[i]
    names(efa_1_plots)[i] <- path_list[i]
    
    # Subset data to only include variables of interest
      formula_select <- formula_list[[i]]
      
      formula_vars <- formula.tools::rhs.vars(formula_select)
      x_vars <- c("ID", "VNUM", "GNUM", "GCHAR", "IQMULL", "DXV24", "DX_AGE", 
                  "DX_GNUM", "DXGENCHA", "IQBIN", formula_vars)
      
      dataset_long_nums <- dataset_long_nums_all %>% 
        filter(Risk_dummy==risk_vals[r]) %>%
        filter(is.na(DXGENCHA)==0) %>%
        filter(eval(parse(text=
                            paste0("!(",
                                   paste0("is.na(",c(formula_vars),")==1", 
                                          collapse = "&"),
                                   ")")
                          )
                      )
                    )
      
      x_var_data <- dataset_long_nums %>%
                select(x_vars)  %>%
                #filter(VNUM%in%c(6,12,24,36)) %>%
                mutate(VNUM_CFA=ifelse(VNUM==6|VNUM==9, 6,
                                      ifelse(VNUM==12|VNUM==15, 12, VNUM))) %>%
                data.frame()
      counter <- 1
    
      for(j in 1:length(data_subset)){
        for(l in 1:length(timepoints)){
          for(m in 1:(length(iq_threshold)+1)){
    
            mplus_path <- "~/Documents/Research/UNC/Sex_Diffs/mnlfa_results"
            setwd(mplus_path)
            mplus_path_model <- paste0(mplus_path, "/", path_list[i])
            
            if(timepoints[l]%in%c("6","12")){
              formula_vars_timespecific <- 
                formula_vars[!grepl("ADOS",formula_vars)]
            }else{
                if(timepoints[l]%in%c("24","36")){
                  formula_vars_timespecific <- 
                  formula_vars[!grepl("aosi",formula_vars)]
                }else{
                  formula_vars_timespecific <- formula_vars
                }
              }
            
            # Conduct CFA on measures, specifying 1 factor. 
            # Use lavaan to deal with missing data using ML
            
            # First select calibration sample of all independent observations
            sample_select <- function(mrdata, myID="ID"){
              set.seed(123)
              mrdata$ranuni <- stats::runif(dim(mrdata)[1], min = 0, 
                      max = 1)
                  mrdata <- mrdata[order(mrdata[myID], mrdata$ranuni),]
                  srdata <- mrdata[!duplicated(mrdata[myID]), ] %>%
                    select(-ranuni)
                  srdata <- as.data.frame(srdata) 
            }
            
            x_var_data_forcalib <-
              if(data_subset[j]=="whole"){
                x_var_data
                }else{
                if(data_subset[j]=="female"){
                  x_var_data %>% filter(GCHAR=="female")
                }else{
                  x_var_data %>% filter(GCHAR=="male")
                }
              }
            
            set.seed(123)
            # Create separate ones for both sexes to calc. different covariance ests.
            calib_sample  <- 
               if(timepoints[l]=="all"){
                 if(iq_threshold=="all"){
                   sample_select(x_var_data_forcalib)
                 }else{
                   if(m==1){
                    sample_select(x_var_data_forcalib) %>%
                     filter(IQMULL<=iq_threshold[m])
                   }else{
                     sample_select(x_var_data_forcalib) %>%
                     filter(IQMULL>iq_threshold[m-1])
                   }
                 }
               }else{
                 if(iq_threshold=="all"){
                   x_var_data_forcalib %>%
                     filter(VNUM_CFA==as.numeric(timepoints[l]))
                 }else{
                   if(m==1){
                    x_var_data_forcalib %>%
                     filter(VNUM_CFA==as.numeric(timepoints[l])) %>%
                     filter(IQMULL<=iq_threshold[m])
                   }else{
                     x_var_data_forcalib %>%
                     filter(VNUM_CFA==as.numeric(timepoints[l])) %>%
                     filter(IQMULL>iq_threshold[m-1])
                   }
                 }
               }
            
          # Complete EFA and CFA while accounting for missing data using FIML 
          # Fit EFA
           efa_1fact_fit[[i]][[counter]] <- list()
           
           chosen_fit_metrics <- 
             data.frame("cfi"=0, "tli"=0, "ifi"=0, "rmsea"=1)
           
           efa_1fact_model_obj <- 
             paste0('#factor loadings \n ', 
                    path_list[i],"=~ ",paste0(formula_vars_timespecific, 
                                              collapse = " + "),
                    "\n #covariances")
           
           fit_counter <- 0
           fit_converged <- 1
           metric_check <- 0
           add_covariances <- NULL
           large_mi_terms <- matrix("blank")
           
           efa_1fact_fit[[i]][[counter]][["model_formula"]] <- NULL
           
          # Fit model, while fit indices are "bad", stop once good
           while(metric_check==0&fit_converged==1){
             
             print(fit_counter)
             
              efa_1fact_fit[[i]][[counter]][["model_formula"]] <- 
               c(efa_1fact_fit[[i]][[counter]][["model_formula"]],
                 efa_1fact_model_obj)
               
              efa_1fact_fit[[i]][[counter]][["est_cov_matrix_fiml"]] <-
               inspectSampleCov(efa_1fact_model_obj, data=calib_sample,
                    missing="fiml")$cov
             
              efa_1fact_fit[[i]][[counter]][["fit_obj"]] <- 
                if(timepoints[l]=="all"){
                  cfa(efa_1fact_model_obj, data=calib_sample, meanstructure=TRUE,
                    missing="fiml")
                }else{
                  cfa(efa_1fact_model_obj, data=calib_sample, meanstructure=TRUE, 
                    ordered = formula_vars)
                }
              
              efa_1fact_fit[[i]][[counter]][["fit_summary"]] <-
                summary(efa_1fact_fit[[i]][[counter]][["fit_obj"]], standardized=TRUE,
                        rsquare=TRUE, fit.measures=TRUE)
              
              efa_1fact_fit[[i]][[counter]][["param_ests"]] <-
                parameterEstimates(efa_1fact_fit[[i]][[counter]][["fit_obj"]], 
                                   standardized = TRUE)
              
              efa_1fact_fit[[i]][[counter]][["fit_modindicies"]] <-
                if(efa_1fact_fit[[i]][[counter]][["fit_obj"]]@Fit@converged==TRUE){
                  modindices(efa_1fact_fit[[i]][[counter]][["fit_obj"]])
                }else{
                  "MODEL DID NOT CONVERGE"
                }
              
              iq_thres_name <- ifelse(iq_threshold=="all", "all", 
                                       ifelse(m==1,paste0("below_",iq_threshold[m]),
                              paste0("above_",iq_threshold[m-1])))
              
                if(efa_1fact_fit[[i]][[counter]][["fit_obj"]]@Fit@converged==TRUE){
                  efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]] <- 
                data.frame("model"=path_list[i],
                           "subset"=data_subset[j],
                           "timepoint"=timepoints[l],
                       "iq_threshold"=iq_thres_name,
                           "fit_index"=
                         names(fitMeasures(efa_1fact_fit[[i]][[counter]][["fit_obj"]])),
                           "value"=as.numeric(
                             fitMeasures(efa_1fact_fit[[i]][[counter]][["fit_obj"]])),
                       "formula"=efa_1fact_model_obj,
                       "covariances_added"=
                         grepl("~~",efa_1fact_model_obj))
                  row.names(efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]]) <- NULL
                }else{
                  efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]] <-
                  "MODEL DID NOT CONVERGE"
                }
              
              fit_converged <- 
                if(length(efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]])==
                         1){
                  0
                }else{
                  1
                }
              
              # Use mod indices to see if fit can be improved using residual 
              # item covariances.  If so, restart process with updated model
            chosen_fit_metrics <- 
              if(efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]]!=
                 "MODEL DID NOT CONVERGE"){
                efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]] %>%
                  filter(fit_index%in%c("cfi","tli","ifi","rmsea")) %>%
                  select(fit_index, value) %>%
                  mutate(id=1) %>%
                  pivot_wider(id_cols=id, names_from = fit_index, values_from = value)
              }else{
                "MODEL DID NOT CONVERGE"
              }
            
            fit_counter <- fit_counter+1
            
            efa_1fact_fit[[i]][[counter]][["iterations"]] <- 
              fit_counter
            
            # Add check if loop ends due to metrics checking out
            if(length(chosen_fit_metrics)>1){
              if(chosen_fit_metrics$cfi<0.89|chosen_fit_metrics$tli<0.89|
                chosen_fit_metrics$ifi<0.89|chosen_fit_metrics$rmsea>0.09){
                metric_check <- 0
              }else{
               metric_check <- 1
             }
            }else{
              metric_check <- 0
            }
            
            # Save piece to add covariances.  If loop repeats, will add them to
            # formula
            large_mi_terms <- 
              if(efa_1fact_fit[[i]][[counter]][["fit_modfit_stats"]]!=
                 "MODEL DID NOT CONVERGE"){
                efa_1fact_fit[[i]][[counter]][["fit_modindicies"]][
                  which(efa_1fact_fit[[i]][[counter]][["fit_modindicies"]]$mi==
                          max(efa_1fact_fit[[i]][[counter]][["fit_modindicies"]]$mi)),
                ]
              }else{ 
                NULL
              }
              
            add_covariances <- 
              if(is.null(large_mi_terms)==0){
                      paste(large_mi_terms$lhs, large_mi_terms$op, large_mi_terms$rhs)
              }else{
              NULL
              }
            
            efa_1fact_model_obj <- paste(efa_1fact_model_obj, 
                                         "\n",
                                         paste0(add_covariances, collapse="\n "))
        
           }
           
           # Create matrix to save final model names for reference
           efa_1fact_fit[[i]][[counter]][["final_models"]] <-
             data.frame(
               "model"=path_list[i],
               "subset"=data_subset[j],
               "timepoint"=timepoints[l],
               "iq_threshold"=iq_thres_name,
               "formula"=efa_1fact_fit[[i]][[counter]][["model_formula"]][
                 length(efa_1fact_fit[[i]][[counter]][["model_formula"]])
               ],
               "covariances_add"=grepl("~~",
                                       efa_1fact_fit[[i]][[counter]][["model_formula"]][
                 length(efa_1fact_fit[[i]][[counter]][["model_formula"]])
               ]))
            
          png(paste0(mplus_path,"/",
              path_list[i],"/plots/efa_scree_plot_", risk_vals[r], "_",
              data_subset[j],"_timept_",timepoints[l],
              "_IQ_",
              iq_thres_name,".png")) 
                  dev.control(displaylist="enable")
                  est_cov_matrix <-
                    efa_1fact_fit[[i]][[counter]][["est_cov_matrix_fiml"]]
                  plotuScree(x=eigen(est_cov_matrix)$values,
                             model="factors")
                  efa_scree_plots[[i]][[counter]] <- recordPlot()
          dev.off()
            
            # Name FA fits
            names(efa_scree_plots[[i]])[counter] <- 
              paste0(data_subset[j],"_timept_",timepoints[l],
                     "_IQ_",
                     iq_thres_name)
            
            # Create plots to share CFA results, include both loadings as bar plots and 
            # scree plot.  Using standardized loadings based on variances of obs and
            # latent variables
            efa_1fact_fit[[i]][[counter]][["loading_matrix"]] <- 
              data.frame("variable"=
                           paste0(efa_1fact_fit[[i]][[counter]][["param_ests"]]$lhs,
                                  efa_1fact_fit[[i]][[counter]][["param_ests"]]$op,
                                  efa_1fact_fit[[i]][[counter]][["param_ests"]]$rhs),
                         "param_ests"=
                           efa_1fact_fit[[i]][[counter]][["param_ests"]]$std.all) %>%
              filter(grepl("=~",variable)) %>% 
              mutate(subset=data_subset[j],
                     timepoint=timepoints[l],
                     iq_threshold=iq_thres_name,
                     variable=gsub(paste0(path_list[i],"=~"),"",variable))
            row.names(efa_1fact_fit[[i]][[counter]][["loading_matrix"]])=NULL
            
            aosi_indicies <- 
              which(grepl("aosi",
                    efa_1fact_fit[[i]][[counter]][["loading_matrix"]][["variable"]]))
            
            efa_1fact_fit[[i]][[counter]][["loading_matrix"]][["variable"]][aosi_indicies]  <-
            lapply(str_split(efa_1fact_fit[[i]][[counter]][["loading_matrix"]]
                      [["variable"]][aosi_indicies],"_"),
                   function(x){paste(x[c(1,2)], collapse = "_")}) %>%
              toupper()
          
            
            efa_1_plots[[i]][[counter]] <- 
              annotate_figure(
                ggarrange(ggplot(data=efa_1fact_fit[[i]][[counter]][["loading_matrix"]], 
                               mapping=aes(x=variable, y=param_ests))+
                          geom_bar(stat = "identity")+
                            xlab("")+
                          theme_bw()+
                            theme(axis.text.x = element_text(angle = 45, 
                                                             vjust = 1, hjust=1)),
                        ggplot(data=data.frame("factor"=
                                                 1:length(eigen(est_cov_matrix)$values),
                                               "eigenvalue"=
                                                 eigen(est_cov_matrix)$values),
                               mapping=aes(x=factor, y=eigenvalue))+
                          geom_point()+
                          geom_path()+
                          theme_bw(), 
                        ncol = 1),
                top=text_grob(paste0(risk_vals[r], "\n", data_subset[j],"\n",
                                     "_timept_",timepoints[l], "\n",
                     "_IQ_", iq_thres_name), 
                     face="bold", size = 14))
            names(efa_1_plots[[i]])[counter] <-
              paste0(data_subset[j],"_timept_",timepoints[l],
                     "_IQ_",
                     iq_thres_name)
            counter = counter+1
          }
        }
      }
      
      # Group results by time
      efa_1_full_plots[[i]] <- list() 
      names(efa_1_full_plots)[i] <- path_list[i]
      
      for(j in 1:length(timepoints)){
        efa_1_full_plots_timefilter <- 
          which(grepl(paste0("timept","_",timepoints[j]),names(efa_1_plots[[i]])))
        
          efa_1_full_plots_listfilter <- list()
          for(l in 1:length(efa_1_full_plots_timefilter)){
            efa_1_full_plots_listfilter[[l]] <- 
              efa_1_plots[[i]][[efa_1_full_plots_timefilter[l]]]
            
            names(efa_1_full_plots_listfilter)[l] <- 
              names(efa_1_plots[[i]])[efa_1_full_plots_timefilter[l]]
          }
        
        unique_plots <- which(str_detect(names(efa_1_full_plots_listfilter),
                unique(names(efa_1_full_plots_listfilter))))
        
        efa_1_full_plots_listfilter_unique <- list()
        for(l in 1:length(unique_plots)){
          efa_1_full_plots_listfilter_unique[[l]] <-
            efa_1_full_plots_listfilter[[unique_plots[l]]]
          
          names(efa_1_full_plots_listfilter_unique)[l] <-
            names(efa_1_full_plots_listfilter)[unique_plots[l]]
        }
    
        efa_1_full_plots[[i]][[j]] <- 
          ggarrange(plotlist = efa_1_full_plots_listfilter_unique,
                    ncol = length(efa_1_full_plots_listfilter_unique))
        
        names(efa_1_full_plots[[i]])[j] <- paste0("timept_",timepoints[j],
                                                  "IQthres_", iq_threshold)
        
        # Create factor loading plot with scree plots
        ggsave(efa_1_full_plots[[i]][[j]], filename =
                 paste0("Plots_Tables/",
                        path_list[[i]],
                        "/cfa_1fac_IQthres_",
                          iq_threshold,"_",
                          paste0("timept_",timepoints[j]),
                          "_", risk_vals[r],
                          "_plot.jpg"),
               width=22.2, height=10, limitsize = FALSE)
      }
        
        # Create paneled factor loading plots
      if(iq_threshold==median(dataset_long_nums$IQMULL, na.rm=TRUE)){
        loading_coefs_dfs <- list()
    
        # First create dataset of all factor loadings across time, sex, iq
        for(l in 1:length(efa_1fact_fit[[i]])){
          loading_coefs_dfs[[l]] <- efa_1fact_fit[[i]][[l]][["loading_matrix"]]
        }
        
        loading_coefs_df <- do.call("rbind", loading_coefs_dfs) %>%
          filter(timepoint!="all"&subset!="whole")  %>% 
          mutate(timepoint=ifelse(timepoint=="6", "06", 
                                  timepoint))
        
        # Plot across time, by gender
        loading_coefs_df_time_gender <- loading_coefs_df %>%
          filter(subset%in%c("female", "male")&timepoint!="all") %>%
          filter(variable %in% harmonized_vars)
        
        ggplot(data=loading_coefs_df_time_gender,
               mapping=aes(x=variable, y=param_ests))+
          facet_grid(subset~timepoint)+
          geom_bar(stat="identity") +
          xlab("Item") +
          ylab("Standardized Loading") +
          labs(title =
                 paste0("Standardized loadings for 1-factor CFAs\nof harmonized ",
                        ifelse(path_list[[i]]=="all_social",
                               "Social items", "RRB items"),
                        " across time by sex")) +
          theme_bw() +
          theme(axis.text.x = element_text(angle = 45, hjust=1),
                text = element_text(size=20))
          ggsave(filename = paste0("Plots_Tables/",
                                   path_list[[i]], "_", risk_vals[r],
                                   "/cfa_std_loadings_bytime_sex.jpg"),
                 scale=2.5,
                 limitsize = FALSE)
          
        
        # Plot at 24 months
        loading_coefs_df_24m <- loading_coefs_df %>%
          filter(timepoint=="24") %>%
          mutate(subset=factor(subset)%>%
                   plyr::revalue(c("female"="Female",
                                   "male"="Male")),
                 iq_threshold=factor(iq_threshold)%>%
                   plyr::revalue(c("above_98"="Above Median IQ",
                                   "below_98"="Below Median IQ")))
        
        ggplot(loading_coefs_df_24m, 
               mapping = aes(x=variable, y=param_ests, fill=subset)) +
          facet_grid(subset~iq_threshold) +
          geom_bar(stat="identity") +
          scale_fill_discrete(name="Sex") +
          xlab("Item") +
          ylab("Standardized Loading") +
          labs(title = 
                 paste0("Standardized loadings for 1-factor CFAs of ADOS ", 
               ifelse(path_list[[i]]=="all_social", "Social ", "RRB "), 
               "items at 24 months,\nby above or below median IQ (98) and infant 
               sex (female or male)")) +
          theme_bw() +
          theme(axis.text.x = element_text(angle = 45, hjust=1))
          ggsave(filename = paste0("Plots_Tables/", 
                 path_list[[i]],
                 "/cfa_std_loadings_24m_", risk_vals[r], ".jpg"),
                 limitsize = FALSE,
                 scale=2.5)
          
      # Look at mean and spread of factor scores across time, sex, and IQ
      # Paneled by IQ
      # Extract factor scores for all models, then bind into full dataset
      factor_scores_dfs <- list()
      for(l in 1:length(efa_1fact_fit[[i]])){
        factor_scores_dfs[[l]] <- 
          data.frame("scores"=lavPredict(object=efa_1fact_fit[[i]][[l]][["fit_obj"]],
                                   method="ML"),
               "timepoints"=efa_1fact_fit[[i]][[l]][["final_models"]]$timepoint,
               "subset"=efa_1fact_fit[[i]][[l]][["final_models"]]$subset,
               "iq_threshold"=efa_1fact_fit[[i]][[l]][["final_models"]]$iq_threshold
               )
        }
      }
      
      # Look at useful fit objects as well as table
      fit_stats_df_all <- list()
      final_models_df_all <- list()
      
      for(j in 1:(length(efa_1fact_fit[[i]])-1)){
        if(j==1){
          if(efa_1fact_fit[[i]][[j]]$fit_modfit_stats!="MODEL DID NOT CONVERGE"){
            fit_stats_df_all[[i]] <- efa_1fact_fit[[i]][[j]]$fit_modfit_stats
            final_models_df_all[[i]] <- efa_1fact_fit[[i]][[j]]$final_models
            }
        }else{
          if(efa_1fact_fit[[i]][[j]]$fit_modfit_stats!="MODEL DID NOT CONVERGE"){
            fit_stats_df_all[[i]] <- rbind(fit_stats_df_all[[i]],
                                  efa_1fact_fit[[i]][[j]]$fit_modfit_stats)
            final_models_df_all[[i]] <- rbind(final_models_df_all[[i]],
                                         efa_1fact_fit[[i]][[j]]$final_models)
            }
          }
      }
      
      fit_stats_df_all_long <- 
        fit_stats_df_all[[i]] %>% 
        distinct() %>%
        filter(fit_index%in%c("chisq","df","pvalue",
                              "cfi","tli","ifi",
                              "srmr",
                              "rmsea", "rmsea.ci.lower", "rmsea.ci.upper"))
      
      fit_stats_df_all_wide <-
        fit_stats_df_all_long %>%
        filter(fit_index!="df") %>%
          pivot_wider(id_cols = c("model","subset","timepoint","iq_threshold",
                                  "formula","covariances_added"),
                      names_from = "fit_index",
                      values_from = "value") %>%
        mutate(rmsea = ifelse(rmsea<0.005, "<0.005", round(rmsea,3)),
               rmsea.est.ci = paste0(rmsea,
                                     " (", round(rmsea.ci.lower,3), ", ",
                                     round(rmsea.ci.upper,3),")"))
      # Look at any with missing fit stats
      missing_pvals_indices <- which(is.na(fit_stats_df_all_wide$pvalue)==1)
        
        # Extract visit time, sex, iq thresholds for missing stats
        missing_pvals_spots <- fit_stats_df_all_wide[missing_pvals_indices,] %>%
          select(subset, timepoint, iq_threshold)
        
      # As table
      flextable(fit_stats_df_all_wide %>% 
              select(-c("rmsea", "rmsea.ci.lower","rmsea.ci.upper", "iq_threshold", "formula")) %>%
              filter(!(subset=="whole"|timepoint=="all")) %>%
              mutate(model=str_to_title(gsub("all_", "", model)),
                     subset=str_to_title(subset),
                     timepoint=paste0(timepoint, " months"),
                     covariances_added=ifelse(covariances_added==TRUE, "Yes", "No")) %>%
              data.frame()) %>%
        hline(i=seq(from=1, to=dim(fit_stats_df_all_wide %>% filter(!(subset=="whole"|timepoint=="all")))[1], by=sum(timepoints!="all"))[-1]-1,
              border = fp_border(color="black")) %>%
        merge_v(j=c("model", "subset")) %>%
        valign(j=c("model", "subset"), valign="top") %>%
        colformat_double(digit=3) %>%
        set_header_labels(values=list(model="Model", timepoint="Visit", subset="Sex", covariances_added="Covariances Added",
                                      chisq="Chi-square", pvalue="P-value", cfi="CFI", tli="TLI", ifi="IFI", srmr="SRMR", 
                                      rmsea.est.ci="RMSEA (95% CI)")) %>%
        fix_border_issues() %>%
        autofit() %>%
        save_as_docx(path=paste0("Plots_Tables/",
                        path_list[[i]],
                        "/cfa_1fac_IQthres_",
                        iq_threshold, "_", risk_vals[r],
                        "_fit_stats.docx"))
      
      # Rename items to fit with aMNLFA/Mplus specs
      # Only doing for HR
      # Using age instead of visit
      dataset_long_nums <- dataset_long_nums_all %>% 
        filter(Risk_dummy=="HR") %>%
        filter(is.na(DXGENCHA)==0) %>%
        filter(eval(parse(text=
                            paste0("!(",
                                   paste0("is.na(",c(formula_vars),")==1", 
                                          collapse = "&"),
                                   ")")
                          )
                      )
                    )
      
      x_var_data <- dataset_long_nums %>%
                select(c("VNUM", "Candidate_Age", x_vars)) %>%
                plyr::rename(c("Candidate_Age"="AGE")) %>%
                data.frame()
      
      x_vars <- names(x_var_data)
      
      names(x_var_data)[grepl("aosi",names(x_var_data))] <- 
        lapply(str_split(names(x_var_data)[grepl("aosi",names(x_var_data))],"_"),
               function(x){paste(x[c(1,2)], collapse = "")}) %>%
        toupper()
      
      names(x_var_data) <- str_replace(names(x_var_data), "AOSI", "")
      
      names(x_var_data)[grepl("ADOS",names(x_var_data))] <-
        substr(x=lapply(str_split(names(x_var_data)[grepl("ADOS",
                                                          names(x_var_data))],"_"),
               function(x){paste(x[c(1,3)], collapse = "")}) %>%
        toupper(), start = 1, stop=8)
      
        names(x_var_data) <- 
          substr(str_replace(names(x_var_data), "ADOS", "Q"), start=1, stop=8)
        
        # Create 3 binary variables to represent ASD*Sex interaction
        x_var_data <- x_var_data %>%
          mutate(DX_G1=ifelse(DXGENCHA=="female_ASD",1,
                                  ifelse(is.na(DXGENCHA)==1, NA, 0)),
                 DX_G2=ifelse(DXGENCHA=="male_negative",1,
                                  ifelse(is.na(DXGENCHA)==1, NA, 0)),
                 DX_G3=ifelse(DXGENCHA=="male_ASD",1,
                                  ifelse(is.na(DXGENCHA)==1, NA, 0)))
        
      items <- 
        names(x_var_data)[-which(names(x_var_data)%in%
                                   c("ID","AGE","VNUM","GNUM","GCHAR","IQMULL",
                                     "DXV24", "DX_GNUM", "DX_AGE", "DXGENCHA",
                                     "IQBIN", "DX_G1", "DX_G2", "DX_G3"))]
    
      write.dat(x = x_var_data, path = mplus_path)
    }
}

# Start MNLFA fit, incorporate into loop
# Create fit obj
library(aMNLFA)
# x_var_data %>%
#   group_by(VNUM, GCHAR) %>%
#   summarise(mean_Q5=mean(Q5, na.rm=TRUE),
#             mean_Q9=mean(Q9, na.rm=TRUE))

# Save IDs for this to see if in new data get the same
#ids_from_old <- x_var_data %>% select(ID, VNUM)

# Look at relationship between IQ, DX, GCHAR for colinearity
ftable(x_var_data$GCHAR, x_var_data$DXV24, x_var_data$IQBIN)
ftable(x_var_data$GCHAR, x_var_data$DXV24) # Looks ok
ftable(x_var_data$GCHAR, x_var_data$IQBIN)

  mnlfa_obj <-
  aMNLFA.object(dir = mplus_path,
                mrdata = x_var_data %>% 
                  #filter(VNUM%in%c(6,12,24,36)) %>%
                  filter(eval(parse(text=
                        paste0("!(",
                               paste0("is.na(",c(items),")==1", 
                                      collapse = "&"),
                               ")")
                      )
                  )
                ) %>% 
                  filter(is.na(DXGENCHA)==0),
                indicators = items,
                catindicators =
                  items,
                time = "AGE",
                # Both result in same estimated scores,
                # but test different relationships
                #meanimpact = c("GNUM", "AGE", "DXV24"), 
                meanimpact = c("AGE", "DX_G1", "DX_G2", "DX_G3", "IQBIN"),
                varimpact = "AGE",
                measinvar = c("GNUM", "AGE", "DXV24"),
                factors = "GCHAR",
                ID = "ID",
                thresholds = FALSE)
  
  # for Social set thresholds=TRUE 
  
  # #spline model to look at where DIF occurs in time
  # #Add spline terms to data set
  # x_var_data_spline <- x_var_data %>%
  #   mutate(age_cutoff = as.numeric(12 <= AGE)*(AGE-12),
  #          V02 = as.numeric(24 <= AGE)*(AGE-24),
  #          V03 = as.numeric(36 <= AGE)*(AGE-36))
  # 
  # write.dat(x = x_var_data_spline, path = mplus_path)
  # mnlfa_obj <-
  # aMNLFA.object(dir = mplus_path,
  #               mrdata = x_var_data_spline %>% filter(eval(parse(text=
  #                       paste0("!(",
  #                              paste0("is.na(",items,")==1",
  #                                     collapse = "&"),
  #                              ")")
  #                     )
  #                 )
  #               ),
  #               indicators = items,
  #               catindicators =
  #                 items,
  #               time = "AGE",
  #               # Both result in same estimated scores,
  #               # but test different relationships
  #               meanimpact = c("GNUM", "AGE", "DXV24", "DX_GNUM", "IQBIN"),
  #               #meanimpact = c("AGE", "DX_G1", "DX_G2", "DX_G3", "IQBIN"),
  #               varimpact = "GNUM",
  #               measinvar = c("GNUM", "AGE", "V01", "V02", "V03"),
  #               factors = "GCHAR",
  #               ID = "ID",
  #               thresholds = FALSE)
  
  # Plots of items by factors
  aMNLFA.itemplots(mnlfa_obj)

  # Create calibration sample (randomly choose 1 obs. per subject)
  # Set seed
  set.seed(123)
  aMNLFA.sample(mnlfa_obj)
  
  # Load edited aMNLFA functions
  detach("package:aMNLFA", unload = TRUE)
  files.sources = list.files(paste0(mplus_path,"/aMNFLA_edit_fns/"), 
                             full.names = TRUE)
  sapply(files.sources, source)

  # Create initial model objs
  aMNLFA.initial(mnlfa_obj)
  #run models (inp files) in MPlus

  # Read-in output from initial models and generate input file for simultaneous models
  aMNLFA.simultaneous(mnlfa_obj)
  # run simultaneous models
  #run models (inp files) in MPlus

  # read-in sim. model results and run multiple comp. corrections, eliminate insig.
  # variables
  aMNLFA.final(mnlfa_obj)
  #run models (inp files) in MPlus

  # read-in final model results, compute final scores
  aMNLFA.scores(mnlfa_obj)
  #run models (inp files) in MPlus
  
  # Plot factor scores
  aMNLFA.scoreplots(mnlfa_obj)
  
  # Plot score trajectories
  ggplot(data=data_plus_scores%>%
           filter(is.na(DXGENCHA)==0), 
         mapping=aes(x=AGE, y=ETA, color=DXGENCHA))+
    geom_point()+
    stat_smooth(aes(group=ID), geom='line', alpha=0.35, se=FALSE, method="lm")+
    geom_smooth(aes(group=DXGENCHA), method="lm", se=FALSE, size=2)+
    labs(title="Predicted social factor scores from MNLFA model\ncolored by sex and diagnosis, LOESS smoothed lines provided",
         color="Gender")+
    ylab("Predicted social factor score")+
    xlab("Age (months)")+
    scale_color_discrete(labels = 
                         c("female_ASD" = "Female ASD",
                           "female_negative" = "Female Negative",
                           "male_ASD" = "Male ASD",
                           "male_negative" = "Male Negative"))+
    theme_bw()+
    theme(text = element_text(size=20))
  ggsave("mnlfa_results/mnlfa_score_scatter.jpg",
         limitsize = FALSE, scale=2.5)
  
  # Plot score boxplots
  data_plus_scores_grouped_age <- 
    data_plus_scores %>%
           mutate(AGE_GROUP=
                    factor(ifelse(AGE<10, "6 and 10 months",
                          ifelse(10<=AGE&AGE<=16, "10 and 16 months",
                                ifelse(22<=AGE&AGE<=28, "22 and 28 months",
                                       ifelse(34<=AGE&AGE<=40, 
                                              "34 and 40 months",
                                              ifelse(is.na(AGE)==1,NA,
                                                     "out of range"))))),
                          levels=c("6 and 10 months", "10 and 16 months",
                                   "22 and 28 months", "34 and 40 months",
                                   "out of range"))) %>%
    filter(is.na(AGE)==0)
  
  # First test sex comparisons within each age group
  aov_fits <- list()
  aov_fits_ttest_df <- 
    data.frame("AGE_GROUP"=unique(data_plus_scores_grouped_age$AGE_GROUP),
               "DXGENCHA"=NA)

  aov_fits_ttest_df["pairwise_diff"] <- NA
  for(i in 1:length(unique(data_plus_scores_grouped_age$AGE_GROUP))){
    # Fit anova for group diffs at time point
    aov_fits[[i]] <- aov(ETA~DXGENCHA, 
        data=data_plus_scores_grouped_age %>%
          filter(is.na(DXGENCHA)==0)%>%
          filter(AGE_GROUP==unique(data_plus_scores_grouped_age$AGE_GROUP)[i]))
    
   aov_fits_ttest_df$pairwise_diff[i] <- summary(aov_fits[[i]])[[1]][["Pr(>F)"]][1]
  }
  
  ggplot(data=data_plus_scores_grouped_age %>% 
           filter(is.na(DXGENCHA)==0), 
         mapping=aes(x=AGE_GROUP, y=ETA, fill=DXGENCHA))+
    geom_boxplot()+
    labs(title="Predicted social factor scores boxplots from MNLFA model\ncolored by sex and diagnosis, grouped by age (months), sex and diagnosis",
         fill="Gender")+
    ylab("Predicted social factor score")+
    xlab("Age (months)")+
    scale_fill_discrete(labels = 
                         c("female_ASD" = "Female ASD",
                           "female_negative" = "Female Negative",
                           "male_ASD" = "Male ASD",
                           "male_negative" = "Male Negative"))+
    geom_text(data=aov_fits_ttest_df, aes(x=AGE_GROUP, y=Inf,
              label=ifelse(0.01<=pairwise_diff&pairwise_diff<0.05,"*",                              ifelse(0.001<=pairwise_diff&pairwise_diff<0.01,"**",                              ifelse(pairwise_diff&pairwise_diff<0.001,"***",
                                             "")))),
            vjust = 1,
            color="black", size=8)+
    theme_bw()+
    theme(text = element_text(size=20))
    ggsave("mnlfa_results/mnlfa_score_boxplot.jpg",
           limitsize = FALSE, scale=2.5)

  # Create table of parameter estimates from MNLFA
  MplusOutput_r3 <- 
      unlist(read.delim(file.path(mplus_path,
                           "round3calibration.out",sep=""), 
                 blank.lines.skip=FALSE))
  
  rownames(MplusOutput_r3) <- NULL
  
  start_index <- which(MplusOutput_r3=="MODEL RESULTS")
  end_index <- which(grepl("Variances", MplusOutput_r3))
  
  model_ests <- data.frame(MplusOutput_r3[start_index:(end_index+2)])
  row.names(model_ests) <- NULL
  names(model_ests) <- NULL
  write.table(model_ests, file="mnlfa_results/mnlfa_model_ests.txt",
              sep="\t", row.names = FALSE)
  
  # Save dataset of scores as well
  write_csv(data_plus_scores, file="mnlfa_results/data_plus_scores.csv")
```

# Trajectory analysis

```{r}
# Select model
model_scores <- "all_social"
output_dir <- paste0("traj_results/", model_scores)

# Load factor scores
factor_data <- 
  read_csv(file=paste0("mnlfa_results/", model_scores, "/data_plus_scores.csv"))

factor_data <- 
  factor_data %>%
  select(names(factor_data)[!grepl(".y", names(factor_data))]) %>%
  as.data.frame()

names(factor_data) <- gsub(".x", "", names(factor_data))
factor_data$ETA_Z <- scale(factor_data$ETA)

## Try growth mixture model with latent class-specific random effect distributions
# Try one class for initial values for algo.
gmm1_si <- hlme(ETA_Z~AGE, subject="ID", random=~1+AGE, ng=1, 
               data=factor_data)

# Two classes, try for various starting values
gmm2_si <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_si, 
                     hlme(ETA_Z~AGE, subject="ID", random=~1+AGE,
                          ng = 2, data = factor_data, mixture = ~ AGE, nwg=T))

gmm3_si <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_si,
                     hlme(ETA_Z~AGE, subject="ID", random=~1+AGE,
                          ng = 3, data = factor_data, mixture = ~ AGE, nwg=T))

gmm4_si <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_si,
                     hlme(ETA_Z~AGE, subject="ID", random=~1+AGE,
                          ng = 4, data = factor_data, mixture = ~ AGE, nwg=T))

# make table with results for the models: 
summarytable(gmm1_si, gmm2_si, gmm3_si)

## Try using a simpler model
gmm1_si <- hlme(ETA_Z~AGE, subject="ID", random=~1+AGE, ng=1, 
               data=factor_data)

# Two classes, try for various starting values
gmm2_si <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_si, 
                     hlme(ETA_Z~AGE, subject="ID", random=~1,
                          ng = 2, data = factor_data, mixture = ~ 1, nwg=T))

gmm3_si <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_si,
                     hlme(ETA_Z~AGE, subject="ID", random=~1,
                          ng = 3, data = factor_data, mixture = ~ 1, nwg=T))

gmm4_si <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_si,
                     hlme(ETA_Z~AGE, subject="ID", random=~1,
                          ng = 4, data = factor_data, mixture = ~ 1, nwg=T))

# make table with results for the models: 
summarytable(gmm1_si, gmm2_si, gmm3_si)

# Look at one with lowest BIC
summary(gmm2_si)
gmm2_si$pred
gmm_classes <- 
  left_join(gmm2_si$pprob, factor_data %>% 
              select(ID, DXGENCHA, GCHAR, ETA, AGE, VNUM)) %>%
  mutate(dx_char = ifelse(grepl("ASD", DXGENCHA), "ASD",
                           ifelse(grepl("negative", DXGENCHA), "Neg", NA)),
         class = factor(class))

# Look at frequencies, summ stats
class_1_sum <- tbl_summary(data=gmm_classes %>% filter(class==1), by=VNUM,
                           include=c("ETA", "DXGENCHA", "GCHAR", "dx_char",
                                     "AGE", "VNUM"))
class_2_sum <- tbl_summary(data=gmm_classes %>% filter(class==2), by=VNUM,
                           include=c("ETA", "DXGENCHA", "GCHAR", "dx_char",
                                     "AGE", "VNUM"))
tbl_merge(tbls = list(class_1_sum, class_2_sum),
          tab_spanner = c("Class 1", "Class 2"))

# Look at factor scores
# Boxplot
ggplot(data=gmm_classes %>% filter(VNUM%in%c(6,12,24,36)), 
       mapping=aes(x=class, y=ETA, fill=class))+
  geom_boxplot()+
  facet_grid(VNUM~DXGENCHA)+
  theme_bw()+
  theme(text=element_text(size=25))
ggsave(filename=paste0(output_dir, "/plots_tables/eta_byclass_boxplot.jpg"),
       scale=2, limitsize = FALSE)

# Plot over time
ggplot(data=gmm_classes, mapping=aes(x=AGE, y=ETA, color=DXGENCHA))+
  geom_point()+
  geom_smooth(mapping = aes(by=ID), method="lm", se=FALSE)+
  facet_grid(~class)+
  theme_bw()+
  theme(text=element_text(size=25))
ggsave(filename=paste0(output_dir, "/plots_tables/eta_byclass_age_trajs.jpg"),
       scale=2, limitsize = FALSE)
```

```{r}
# Look at distributions of factor scores by visit, gender, diagnosis
score_types <- c("all_social", "all_rrb")
summary_stats_eta_matrix <- list()
eta_sample_sizes_matrix <- list()

for(i in 1:length(score_types)){
  score_type <- score_types[i]
  factor_score_data <- 
    read_csv(paste0("mnlfa_results/", score_type, "/data_plus_scores.csv")) 
  
  factor_score_data <- factor_score_data %>%
    select(-names(factor_score_data)[grepl(".y", names(factor_score_data))])  %>%
    mutate(DXGENCHA=fct_recode(factor(DXGENCHA),
                               `Male ASD`="male_ASD", `Female ASD`="female_ASD",
                               `Male Neg`="male_negative", `Female Neg`="female_negative"))
  
  names(factor_score_data) <- gsub(".x", "", names(factor_score_data))
  summary_stats_eta <- factor_score_data %>%
    group_by(VNUM, GCHAR, DXV24) %>%
    summarise(mean_eta = mean(ETA, na.rm=TRUE),
              sd_eta = sd(ETA, na.rm=TRUE),
              n=n()) %>%
    mutate(DXV24 = ifelse(DXV24==0, "Negative", "ASD"),
           GCHAR = str_to_title(GCHAR)) %>%
    mutate(VNUM_GCHAR_DXV24 = paste0(VNUM, "_", GCHAR, "_", DXV24),
           mean_sd_eta = paste0(round(mean_eta, 2), " (", round(sd_eta, 2), ")")) %>%
    ungroup()
  
  summary_stats_eta_header <- summary_stats_eta %>%
    select(VNUM_GCHAR_DXV24, VNUM, GCHAR, DXV24)
  
  summary_stats_eta_header <- rbind(data.frame("VNUM_GCHAR_DXV24"="score",
                                               "VNUM"="", "GCHAR"="",
                                               "DXV24"=""),
                                         summary_stats_eta_header)
  
  summary_stats_eta <- summary_stats_eta %>%
    select(VNUM_GCHAR_DXV24, mean_sd_eta, n)
  
  # Save as list element
  summary_stats_eta_matrix[[i]] <- summary_stats_eta %>% select(mean_sd_eta) %>% t() %>% data.frame()
  summary_stats_eta_matrix[[i]] <- data.frame("score"=score_type, summary_stats_eta_matrix[[i]])
  names(summary_stats_eta_matrix[[i]]) <- summary_stats_eta_header$VNUM_GCHAR_DXV24
  
  eta_sample_sizes_matrix[[i]] <- summary_stats_eta %>% select(n) %>% t() %>% data.frame()
  eta_sample_sizes_matrix[[i]] <- data.frame("score"=score_type, eta_sample_sizes_matrix[[i]])
  names(eta_sample_sizes_matrix[[i]]) <- summary_stats_eta_header$VNUM_GCHAR_DXV24
}
 
summary_stats_eta_matrix <- do.call("rbind", summary_stats_eta_matrix)
eta_sample_sizes_matrix <- do.call("rbind", eta_sample_sizes_matrix)

# Reformat score column
summary_stats_eta_matrix$score <- 
  factor(gsub("all_", "", x=summary_stats_eta_matrix$score)) %>%
  fct_recode(Social="social", RRB="rrb")

eta_sample_sizes_matrix$score <- 
  factor(gsub("all_", "", x=eta_sample_sizes_matrix$score)) %>%
  fct_recode(Social="social", RRB="rrb")
 
# Now move to flextable
flextable(summary_stats_eta_matrix) %>%
  set_header_df(mapping=summary_stats_eta_header, key="VNUM_GCHAR_DXV24") %>%
  merge_v(part = "header", j = c(1,2)) %>% 
  merge_h(part = "header", i = c(1,2)) %>% 
  theme_booktabs(bold_header = TRUE) %>% 
  align(align = "center", part = "all") %>%
  vline(j = c(1, 5, 9, 13), border = fp_border()) %>%
  autofit() %>%
  save_as_docx(path="mnlfa_results/factor_score_sum_stats.docx")

flextable(eta_sample_sizes_matrix) %>%
  set_header_df(mapping=summary_stats_eta_header, key="VNUM_GCHAR_DXV24") %>%
  merge_v(part = "header", j = c(1,2)) %>% 
  merge_h(part = "header", i = c(1,2)) %>% 
  theme_booktabs(bold_header = TRUE) %>% 
  align(align = "center", part = "all") %>%
  vline(j = c(1, 5, 9, 13), border = fp_border()) %>%
  autofit() %>%
  save_as_docx(path="mnlfa_results/factor_score_sample_size.docx")

```
